### ISSUE TITLE
vlingo-ecommerce fails with NPE and goes into endless loop

### ISSUE THREAD

**Issue by anderskristian** [vlingo/vlingo-examples#52]
I am tying to get ecommerce to run.

I have read the documentation. Found **all** sample to go with. 
I have executed the TEST - also fails

I do the following
* Start application by run main in class io.vlingo.examples.ecommerce.Bootstrap
* This will start a web server on port 8081

I am still struggling to understand vlingo - had hoped that I had made my killer banking application now - but I have to be patient.

As said I have read the documentation. That was **quick** - Therefore I have to do things on my own. 

```

curl -X POST -H 'Content-Type: application/json' -d '{"id":319}' http://localhost:8081/cart 

```

The failure is: (tail continues for ever)

```
08:25:37.517 [pool-2-thread-16] INFO  io.vlingo.actors.Logger - io.vlingo.examples.ecommerce.infra.CartSummaryProjectionActor - Query state not read for update because: Store not found: CartUserSummaryData
io.vlingo.symbio.store.StorageException: Store not found: CartUserSummaryData
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.readFor(InMemoryStateStoreActor.java:138) ~[classes/:na]
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.read(InMemoryStateStoreActor.java:113) ~[classes/:na]
	at io.vlingo.symbio.store.state.StateStore__Proxy.lambda$read$9b0a896c$1(StateStore__Proxy.java:46) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53) ~[classes/:na]
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:100) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
08:25:37.517 [pool-2-thread-16] INFO  io.vlingo.actors.Logger - io.vlingo.examples.ecommerce.infra.CartSummaryProjectionActor - Query state not read for update because: Store not found: CartUserSummaryData
io.vlingo.symbio.store.StorageException: Store not found: CartUserSummaryData
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.readFor(InMemoryStateStoreActor.java:138) ~[classes/:na]
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.read(InMemoryStateStoreActor.java:113) ~[classes/:na]
	at io.vlingo.symbio.store.state.StateStore__Proxy.lambda$read$9b0a896c$1(StateStore__Proxy.java:46) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53) ~[classes/:na]
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:100) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
08:25:37.518 [pool-2-thread-16] ERROR io.vlingo.actors.Logger - io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor - InMemoryStateStoreActor writeText() error because: null
java.lang.NullPointerException: null
	at io.vlingo.examples.ecommerce.infra.GenericReadWriteInterest.lambda$writeResultedIn$2(GenericReadWriteInterest.java:41) ~[classes/:na]
	at io.vlingo.common.Success.andThen(Success.java:29) ~[classes/:na]
	at io.vlingo.examples.ecommerce.infra.GenericReadWriteInterest.writeResultedIn(GenericReadWriteInterest.java:40) ~[classes/:na]
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.writeWith(InMemoryStateStoreActor.java:200) ~[classes/:na]
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.write(InMemoryStateStoreActor.java:118) ~[classes/:na]
	at io.vlingo.symbio.store.state.StateStore__Proxy.lambda$write$ddcd3901$1(StateStore__Proxy.java:36) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53) ~[classes/:na]
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:100) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
08:25:37.518 [pool-2-thread-16] INFO  io.vlingo.actors.Logger - io.vlingo.examples.ecommerce.infra.CartSummaryProjectionActor - Query state not written for update because: null
io.vlingo.symbio.store.StorageException: null
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.writeWith(InMemoryStateStoreActor.java:203) ~[classes/:na]
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.write(InMemoryStateStoreActor.java:118) ~[classes/:na]
	at io.vlingo.symbio.store.state.StateStore__Proxy.lambda$write$ddcd3901$1(StateStore__Proxy.java:36) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53) ~[classes/:na]
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:100) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.NullPointerException: null
	at io.vlingo.examples.ecommerce.infra.GenericReadWriteInterest.lambda$writeResultedIn$2(GenericReadWriteInterest.java:41) ~[classes/:na]
	at io.vlingo.common.Success.andThen(Success.java:29) ~[classes/:na]
	at io.vlingo.examples.ecommerce.infra.GenericReadWriteInterest.writeResultedIn(GenericReadWriteInterest.java:40) ~[classes/:na]
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.writeWith(InMemoryStateStoreActor.java:200) ~[classes/:na]
	... 8 common frames omitted
```

**Comment by VaughnVernon** [comment]
@anderskristian I suggest updating to platform version `1.2.3` that was just sync'd to Bintray.

Sonatype takes longer and then Maven Central longer still.

**Comment by anderskristian** [comment]
hi @VaughnVernon 

There seems to be a bug in the gradle.build script in **platform** - so it is difficult to see if I have checked correct out from master.

Anyway ...

```
$ cd vlingo-examples
§ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ git pull
Already up to date.

$ cat pom.xml | grep 1.2.3
  <version>1.2.3</version>
```
So I will say I am up to date - so are the other modules

```
mvn clean install   -Dmaven.test.skip=false

20:16:56.239 [pool-15-thread-9] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Server stopped.
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.456 s <<< FAILURE! - in io.vlingo.examples.ecommerce.CartResourceShould
[ERROR] cartIsEmpty_whenCreated(io.vlingo.examples.ecommerce.CartResourceShould)  Time elapsed: 0.057 s  <<< ERROR!
java.lang.NullPointerException
	at io.vlingo.examples.ecommerce.CartResourceShould.setUp(CartResourceShould.java:30)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CartResourceShould.setUp:30 » NullPointer
[INFO] 
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for vlingo-examples 1.2.3:
[INFO] 
[INFO] vlingo-actors-playground ........................... SUCCESS [  2.200 s]
[INFO] vlingo-auth-authservice ............................ SUCCESS [  3.365 s]
[INFO] vlingo-ecommerce ................................... FAILURE [  4.332 s]
[INFO] vlingo-eventjournal ................................ SKIPPED
[INFO] vlingo-http-backservice ............................ SKIPPED
[INFO] vlingo-http-frontservice ........................... SKIPPED
[INFO] vlingo-iddd-agilepm ................................ SKIPPED
[INFO] vlingo-iddd-collaboration .......................... SKIPPED
```

**Comment by VaughnVernon** [comment]
@anderskristian I am pretty sure that your primary issues are around trying to build the platform locally when you should only depend on it. I think if you do the following everything will work well for you.

```
$ rm -rf ~/.m2/repository/io/vlingo/*

$ git clone https://github.com/vlingo/vlingo-examples.git

$ cd vlingo-examples

$ mvn clean test
```

**Comment by anderskristian** [comment]
hi @VaughnVernon
I did this. All jars is not a maven central at the moment.
Then I build the jars local that was missing on central

Then I ran the tests - and the tests runs to the end OK SUPER

* Then remove again rm -rf ~/.m2/repository/io/vlingo/* 
* platform clean install

And now the tests still runs !!!

I believe that the GRADLE script in platform is a problem

Anyway - I have used the entire evening now and ECOMMERCE.BOOTSTRAP is still making NPE's
So I am actually back to start after the 1.2.3 version fight.

My plan was tonight to find out why InMemoryStateStoreActor gets NPE

In general the code is too complex for me. And the lack of an example to follow really gives troubles. 
I cannot see if the test cases are TESTS??? This usage of io.restassured.specification.RequestSpecification - when are we testing? When are we calling the server ? When is it just a memory test? I CANNOT SEE IT !!!!

And the tests are full of stack traces -- is this intensional? I CANNOT SEE IT !!!!

It might be the wrong example I am looking on !!!!
I am done with ping/pong 100% consumed. 
I need some sample that tells med that this actor IDEA is something I can bring to my team!!

Good things. Server startes in 70 ms. You are friendly to answer. thanks for that.

The error:
```
ERROR io.vlingo.actors.Logger - io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor - InMemoryStateStoreActor writeText() error because: null
java.lang.NullPointerException: null
	at io.vlingo.examples.ecommerce.infra.GenericReadWriteInterest.lambda$writeResultedIn$2(GenericReadWriteInterest.java:41) ~[classes/:na]
	at io.vlingo.common.Success.andThen(Success.java:29) ~[classes/:na]
	at io.vlingo.examples.ecommerce.infra.GenericReadWriteInterest.writeResultedIn(GenericReadWriteInterest.java:40) ~[classes/:na]
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.writeWith(InMemoryStateStoreActor.java:200) ~[classes/:na]
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.write(InMemoryStateStoreActor.java:118) ~[classes/:na]
	at io.vlingo.symbio.store.state.StateStore__Proxy.lambda$write$ddcd3901$1(StateStore__Proxy.java:36) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121) ~[classes/:na]
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53) ~[classes/:na]
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:100) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

**Comment by VaughnVernon** [comment]
@anderskristian I see the problem now. The examples don't default to dependencies on Bintray.

You can see for example `vlingo-actors` `README` and it should show you how to point to Bintray. You can then put that in your local `vlingo-ecommerce` example.

**Comment by anderskristian** [comment]
Good morning
Now both jcenter and central gives the artefacts -- SUPER -- and true a developer that only check-out the test will not face these problems..

I now find some new problems in the test CartResourceShould
1) The test will try to run a server on port 9090 next 9091 next 9092
This does not work 100% due to some close server problems

2) Even that it would work then **CartQueryProvider.instance** will return the same **CartQueryProvider** for all three servers.

```

public class CartQueryProvider {
  private static CartQueryProvider instance; <<<<<<<<<<<<<< STATIC

  public final CartQuery cartQuery;
  public final StateStore store;

  public static CartQueryProvider instance() {
    return instance;
  }

```

**Comment by anderskristian** [comment]
I have been looking at the **using()** + static instance() **PATTERN**

This sample got 3 of them - and therefore cannot run more than once in the JVM

I might be wrong - but I also the the **using()** in the **"vlingo-core"**
But in the core I see the **using()** as more a factory pattern - that does **not cache** a singleton.

**Comment by anderskristian** [comment]
We got some quality problems - in my eyes - there should not be logged ERROR in tests even that they passes

**Comment by VaughnVernon** [comment]
Hi @bwehrle When you have a little time, would you please help @anderskristian with your ecommerce example? Thanks much!

**Comment by bwehrle** [comment]
Hi, @anderskristian, I hit a similar problem before, and it had to do with this same issue.  Let me look at this during the evening and should be easy to sort out.  I pressume these singletons need to be cleaned up after shutdown.  There is no DI system here managing the lifecycle, so needs to be done manually, etc.

**Comment by anderskristian** [comment]
Super. If you do update - you are very welcome to describe some curl statements that works in the README.md

I was confused with the tests that is described. RestAssured - does not make sense to me. But anyway I should learn it...

Still I would be glad to see some use-case described in the README.md

**Comment by VaughnVernon** [comment]
@anderskristian Did you see this example? I think it might be more complete as Brian is challenged to get free time. We do appreciate everything Brian has contributed, but we also respect that he has a full-time job and he helps his wife with tech to run her business.

https://github.com/vlingo/vlingo-examples/tree/master/vlingo-http-frontservice#vlingo-http-frontservice

**Comment by anderskristian** [comment]
hi @VaughnVernon

I will take a look at that one ..

I did by the way document vlingo-platform-patterns's README.md 

It is a little jobby to fork the samples and then make a pull request
So I you add me to be able to make pull requests on the source - I can fix / such small things and produce pull you can take in if the changes are correct.
/Anders

**Comment by VaughnVernon** [comment]
Of course. I will add you to our Slack workspace too if you'd like.

**Comment by bwehrle** [comment]
Hi @VaughnVernon, looking at this now.   I sync to the latest versions locally and maven clean/installed.  When I run the tests, I see they pass, but there are repeated errors in the StateStore.  The errors happen because the ProjectionControl.Confirmer is null in the GenericReadWriteInterest.java class, line 40.  Could this be because there was a (breaking?) change in the API wherein the ProjectionControl.Confirmer needs to be passed in to the Store.write?  I assume this is the case and will try this and answer the above questions from Anders above.

```java
 outcome.andThen(result -> {
      ((ProjectionControl.Confirmer) object).confirm();
      return result;
    }).otherwise(cause -> {
```

**Comment by anderskristian** [comment]
@bwehrle @VaughnVernon 
1.2.4 seems to generate some problems
I have tested vlingo-http-backend + vlingo-http-frontend with 1.2.4 and it fails
 - then I have tested with 1.2.1 - and it works

**Comment by anderskristian** [comment]
@bwehrle @VaughnVernon
There is also a compile problem in 
io.vlingo.entity.object.State - it would not compile in 1.2.4 - then I fixed it locally 
In 1.2.1 

In 1.2.4 I had to change

```
@Override
  public Map<String, Object> queryMap() {
    return FluentMap.has("organizationId", organizationId.value);
  }

```

to - I got no Idea if that was a correct change - it complies :-)

```

  @Override
  public Map<String, Object> queryMap() {
    return MapQueryExpression.FluentMap.has("organizationId", organizationId.value);
  }

```

**Comment by bwehrle** [comment]
I found that by adding the last argument to CartSummaryProjectionActor.java:79 the functionality works as expected:
```java
 store.write(nextData.userId, nextData, version, genericReadWriteInterest, control.confirmerFor(projectable));
```
I can make a PR to make this change, unless you believe the problem is solved by down-grading the dependencies.

I still see an error in the logs that I don't believe was showing before.  However, the service code does not see this, it might be a bootstrap "probing" log.  Note that it is logged at INFO level, not ERROR.
```
09:19:53.573 [pool-2-thread-3] INFO  io.vlingo.actors.Logger - io.vlingo.examples.ecommerce.infra.CartSummaryProjectionActor - Query state not read for update because: Store not found: CartUserSummaryData
io.vlingo.symbio.store.StorageException: Store not found: CartUserSummaryData
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.readFor(InMemoryStateStoreActor.java:160) ~[vlingo-symbio-1.2.5.jar:na]
	at io.vlingo.symbio.store.state.inmemory.InMemoryStateStoreActor.read(InMemoryStateStoreActor.java:122) ~[vlingo-symbio-1.2.5.jar:na]
	at io.vlingo.symbio.store.state.StateStore__Proxy.lambda$read$9b0a896c$1(StateStore__Proxy.java:54) ~[vlingo-symbio-1.2.5.jar:na]
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121) ~[vlingo-actors-1.2.5.jar:na]
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53) ~[vlingo-actors-1.2.5.jar:na]
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:100) ~[vlingo-actors-1.2.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]
```
This did not cause a visible test failure.  

@anderskristian : to answer some of the questions/issues raised:

RestAssured:  
This is an easy way to write Given/When/Then tests that talk to HTTP/Rest interfaces.  From these tests the interface should be pretty clear.  Happy to hear suggestions on better libraries to use. 

Errors logged and tests pass: The tests pass because the functionality they are testing works.  This does not mean that there are not missing tests here.  As this is example code, I did not write all of the possible test cases.  As such, when writing production code you would want to cover more of the "adapter" modules.  

Regarding multiple instances of the code inside a single JVM:  If you want to run multiple in the same JVM, please expect some adaption work to handle the different "contexts" inside your application and to adapt the code accordingly.  This issue is "by design".

Regarding ports:  Since the idea is to run test modules that are independent, each one take care of setting up its own vlingo server context - due to potential OS issues with failing tests and late-closing ports, I recommend this.  I saw different "phantom" issues due to lack of synchronization; a synchronous shutdown() method for the server would be useful here.

**Comment by anderskristian** [comment]
@bwehrle @VaughnVernon
I have made pull request https://github.com/vlingo/vlingo-examples/pull/55
It is an improved sample of **vlingo-platform-pattern**

Where I try to stop a server
In 1.2.4 The stop would make a deadletter queue log as crazy, but the intension on stopping the server works ...
In 1.2.1 The mailbox does not go crazy - but the close of one **Server** seems to freeze world

This could be 10 gram related to the ping/pong finding I made ..

**Comment by VaughnVernon** [comment]
@anderskristian @bwehrle I think a PR is best. There have problems problems with actor ctors that have the same number of parameters. As a result we have temporarily eliminated some of the vlingo-symbio ctors that takes only one Dispatcher in favor of the one that takes List<Dispatcher>. This broke some examples in 1.2.4 but are now fixed in 1.2.5. Strangely enough all ctors in the 1.2.4 worked while testing, even on Travis, but then stopped working yesterday even on Travis. So I had to opt for ctors that take List<Dispatcher>. So pull all code for 1.2.5 and I think you'll find some things works better now.

**Comment by anderskristian** [comment]
The restAssured thing ....

This was no blame on your code - just to get that right..

My problem with a tool like restAssured is that it takes knowledge about that tool kit to understand that something is being tested!!!

* Using jUnit4 Assert statements communicates much much better for 3'rd man.
* Local variables in a test also makes it possible to set a breakpoints in the debugger.
* In my eyes a test must **document** in a simple understandable way what it is doing. 
* Writing code lines in a test is at very good thing in my eyes.
* In restAssured I cannot understand when the service was called ..
* I do accept that reactive programming needs some tooling to get the reactive part in a testable state

Therefore a a good test in my eyes ...
1. The test class **do not extent anything** - yours also do not extend anything - OK
2. Assert statements exists in each test to prove what is being tested - rest.assured fails here
3. Mocking makes a test unclear too - so **avoid mocking**. Only to be used in "old systems" - where we cannot get a handle on "the other side"

A library like restAssured could easy be used to collect knowledge about a REST call - BUT the assert statements MUST live in the test it self.  

The when / expect thing is nice.

Here I think that Spock testing is a very good thing. 
Spock also provide a clear "ASSERT" strategy

**Comment by VaughnVernon** [comment]
BTW, we had a fix for the ctors with same number of parameters but there were a few problems with it so it was backed out. @buritos will address this again after we release 1.3.0 in a few days.

**Comment by anderskristian** [comment]
@bwehrle @VaughnVernon

* Downgrading - NO. I just gave 1.2.1 as a hint ...
* By the way did you see my PR I have made pull request #55 - I worked on it 10 hours yesterday - and I am convinced that it is the **world** we should terminate - not various actors - unless there is a business reason for stopping a given actor.

**Comment by anderskristian** [comment]
Hi @bwehrle @VaughnVernon
I have tested vlingo-platform-patterns on both 1.2.1 and 1.2.5
